### ISSUE TITLE
[Enhancement] Working page up / page down

### ISSUE THREAD

**Issue by melroy89** [ThomasVon2021/blikvm#104]
Currently the page up and page down keys are not working in BlikVM for some reason.

Only when using the virtual keyboard I can use page up and page down. Please also support page up/down via the actual keyboard in the BliKVM link web UI.

**Comment by ThomasVon2021** [comment]
Can you update to 1.3.2 to test?

**Comment by melroy89** [comment]
Sure

**Comment by melroy89** [comment]
I don't know what you did. But it is resolved!! Well done.
