### ISSUE TITLE
Firewall issue on CM4 - http and webrtc are blocked by default

### ISSUE THREAD

**Issue by harlong** [ThomasVon2021/blikvm#111]
On just flashed CM4 (image blikvm-v1-v2-v3-20231203.zip, blikvm v1.3.3) ports 80 (http) and 8188 (webrtc) were filtered by default. I had to do this to get webUI work:

sudo -i
rw
iptables -A INPUT -p tcp --dport 80 -j ACCEPT
iptables -A INPUT -p tcp --dport 8188 -j ACCEPT
iptables-save > /etc/iptables/rules.v4

It seems that /etc/iptables/rules.v4 should be corrected in image file

**Comment by ThomasVon2021** [comment]
That is to say, burning the blikvm-v1-v2-v3-20231203.zip to CM4 version, the web cannot be opened? I will test it tonight to see if it works.

**Comment by harlong** [comment]
Yes, it says "connection timed out"
![image](https://github.com/ThomasVon2021/blikvm/assets/116577111/aca450d0-2976-4bd6-803e-de534fab59fb)

![image](https://github.com/ThomasVon2021/blikvm/assets/116577111/0aced993-125f-4d21-9d32-5f8efdc504c9)
The same time in netstat we see, that kvm-link, janus and ustreamer are listening on their ports

And in iptables -L - default policy for INPUT chain is "drop" and ports 80, 8008, 8188 are not explicitly open

**Comment by ThomasVon2021** [comment]
Learned, thank you for explaining. I will update the image tonight.

**Comment by harlong** [comment]
Not confirmed. In the newly flashed image everything works normal. The case was that user occasionly installed firewall by himself.
