### ISSUE TITLE
[Question] Hiding kvm titles on connected computer

### ISSUE THREAD

**Issue by Di9** [ThomasVon2021/blikvm#118]
Hi, everybody!

I've found this project, and looking forward fot using it, but get worries about some kvm titles and mentioning in devices, so it might saved in various logs and I'd like to change the name of usb-interface for something more casual, like keyboard instead of Composite KVM Device :) Is there any options? thx

**Comment by ThomasVon2021** [comment]
https://github.com/ThomasVon2021/blikvm/tree/master/package/kvmd-hid
Do you ask in discord? 
Has the problem been resolved now?
