### ISSUE TITLE
[Feature] hide "webrtc" settings in GUI when SBC doesn't support it

### ISSUE THREAD

**Issue by m50S79sM6SRNp8Jn** [ThomasVon2021/blikvm#133]
Allwinner SBC doesn't support webrtc.
Raspberry Pi does support webrtc.

This feature will be part of upcoming BliKVM Matrix software release (Q2 2024).

**Comment by m50S79sM6SRNp8Jn** [comment]
Thanks for the feature request. We will address this as part of the BliKVM Matrix software release.

**Comment by ThomasVon2021** [comment]
Upgrade to the latest version, and if there are any issues, you can reopen it.
