### ISSUE TITLE
[Bug][v1.3.9][v4] A second web session gets a cryptic error message

### ISSUE THREAD

**Issue by owendelong** [ThomasVon2021/blikvm#135]
Experienced on Blikvm software 1.3.9 on v4

When a second tab is connected to the KVM and logs in, the original tab will get a graphic stating that the device is off line and check network within the blikvm UI. One can still do some things if one tries hard enough, but you cannot get the target screen to work.

Instead of "Device is Offline, CHECK Network!" perhaps it would be better to say "Device is in use by another session" or something to that effect. Ideally provide the IP address of the active remote device.

**Comment by owendelong** [comment]
No reverse proxies... Will see if I can figure out how to record a video.

**Comment by owendelong** [comment]
I was unable to reproduce the problem, but I will try to capture more data if I am able to reproduce.

**Comment by m50S79sM6SRNp8Jn** [comment]
Not able to reproduce.
