### ISSUE TITLE
Update Tailscale

### ISSUE THREAD

**Issue by swingstate** [ThomasVon2021/blikvm#138]
Hi Thomas,

how can I update the Tailscale version from 1.40.1 to the latest 1.5x? Looks like there is no newer package for this distro?

I would like to use the autoupdate feature which got introduced in 1.52.

Thanks

**Comment by ThomasVon2021** [comment]
You can uninstall and reinstall it.

**Comment by swingstate** [comment]
reinstall ends with 1.40.1

**Comment by m50S79sM6SRNp8Jn** [comment]
Have you tried contacting Tailscale on the best course of action?
Please let us know what they said.

**Comment by ThomasVon2021** [comment]
> Have you tried contacting Tailscale on the best course of action?
> Please let us know what they said.

What is your installation method?

**Comment by ThomasVon2021** [comment]
I will close this issue. If you have successfully upgraded, you can Google search for instructions on how to uninstall and install the latest version in a Linux environment.
If there are still issues, you can reopen this issue.

**Comment by masterkain** [comment]
I had to do this:

```
root@blikvm(rw):/home/blikvm# chmod 1777 /tmp
root@blikvm(rw):/home/blikvm# curl -fsSL https://tailscale.com/install.sh | sh
```

furthermore passing `--accept-routes` disables normal lan access for me, had to `tailscale up --accept-routes=false`
