### ISSUE TITLE
How to test new languages

### ISSUE THREAD

**Issue by FrostWalk** [ThomasVon2021/blikvm#140]
Hi, I was writing the Italian translation of the interface, but I didn't find how to test it and check if the words fit the context, before opening a pull request.
Thanks for the help.

**Comment by ThomasVon2021** [comment]
At present, it is indeed not possible to directly test. We suggest that you submit the PR directly. After I send the version, you can test it again if you find any problems. We are refactoring the code so that users can build all the programs themselves in their entirety
