### ISSUE TITLE
[BliKvm V3] Problem of using general USB msd

### ISSUE THREAD

**Issue by KaoTuz** [ThomasVon2021/blikvm#141]
Hi

I have an problem of using general USB msd

I had created a usb and put some file in it by SCP command

and it could see and mount on the target side successfully

But when i want to add new file to the usb by the following two command

1. Copy file to kvm
`scp xxx blikvm@xxxx:/mnt/msd/user/`
2. Sync file and target side
`sudo bash /usr/bin/blikvm/kvmd-msd.sh -c forward`

The new file upload successful to the kvm terminal
But the new file do not sync to the target side,i could not see my new file in my target usb disk

First Transfer <--- It's OK
     I create  an folder efi/boot  and put a file shellx64.efi in path  /mnt/msd/user/efi/boot
Second Transfer  <-- Could not see my new added file
    i delete file shellx64.efi  in path  /mnt/msd/user/efi/boot, and add a file bootX64.efi into path  /mnt/msd/user/efi/boot

is there anything that i need to notice or missing?

Code Release Version : V1.4.0
the Log after executing step2
[Log.txt](https://github.com/ThomasVon2021/blikvm/files/14161544/Log.txt)

**Comment by ThomasVon2021** [comment]
Can you test again without creating subdirectories and only placing files in the path? Based on the code, the script currently does not support creating folders. I want to confirm this.

**Comment by KaoTuz** [comment]
I tried the following procedure and it had wired situation

1. Create 1G usb disk
    ```
   sudo bash /usr/bin/blikvm/kvmd-msd.sh -c make -s 4 -t other
    ```
2. First Transfer , put file by scp command and the file sync properly
![Snipaste_2024-02-05_17-25-20](https://github.com/ThomasVon2021/blikvm/assets/28426509/6540fc76-e7d2-463e-ac3b-99aaae79d0be)

3.  Second Transfer , Add ReadME.md file by scp command and the file sync properly
![Snipaste_2024-02-05_17-28-16](https://github.com/ThomasVon2021/blikvm/assets/28426509/ae3b1f93-d32a-4b49-b705-18408a360eb5)

4. Third Transfer , remove ReadME.md and add LICENSE file , sync incorrectly
![Snipaste_2024-02-05_17-30-39](https://github.com/ThomasVon2021/blikvm/assets/28426509/b4493dd8-f621-409c-ac16-94e3c02b2772)


The deleted file(READNE.ms) sync to target magically, even the file had been removed in kvm terminal

**Comment by ThomasVon2021** [comment]
This is within expectations. You see it as a USB drive, where the files are copied in and the source is deleted, but the files in the USB drive are still there.
Unless you delete it on the target computer.

**Comment by ThomasVon2021** [comment]
May I ask if there are any further discoveries? If not, I plan to improve the readme. Regarding the two usage precautions you have discovered, I will then close the issue.

**Comment by KaoTuz** [comment]
Is there would be an improved for creating sub directories ?

**Comment by ThomasVon2021** [comment]
> Is there would be an improved for creating sub directories ?

https://github.com/ThomasVon2021/blikvm/blob/master/package/kvmd-msd/kvmd-msd.sh

Based on your requirements, we have fixed this issue. Can you manually use the latest script for testing first and then provide feedback on the results?
