### ISSUE TITLE
[Feature request] Make KVM switch channel labels customizable

### ISSUE THREAD

**Issue by mluna0101** [ThomasVon2021/blikvm#145]
In the web interface it would be nice to be able to change the channel button labels to something that makes sense to what is connected to the port instead of just channel numbers.

Say, Channel 1 could be renamed to something like "Main server", Channel 2 to "NAS", Channel 3 to "Hypervisor" and Channel 4 to "Linux".

Maybe it doesn't look too useful but when you escalate it to 8 channels or more then you'll really appreciate that feature, especially if you don't access the KVM that often.

**Comment by ThomasVon2021** [comment]
That's a good suggestion, we will add this feature in future versions.

**Comment by ThomasVon2021** [comment]
https://wiki.blicube.com/blikvm/en/flashing_os/
You can flash the lasted image to test.

**Comment by ThomasVon2021** [comment]
The latest v1.4.4 version has been tested and is now supported. If there are any issues, you can reopen it.
