### ISSUE TITLE
Blikvm not boot to OS : 

### ISSUE THREAD

**Issue by irish1986** [ThomasVon2021/blikvm#154]
I am unable to get my blikvm v3 HAT to work.  I have tried both version of the OS and it always fails (get stuck here). I tried this RPi4 ith Ubuntu server and it booted well.  Any suggestion ?

![image](https://github.com/ThomasVon2021/blikvm/assets/13018674/2dc8aff8-2834-48b1-a824-90bd10425248)

**Comment by m50S79sM6SRNp8Jn** [comment]
Can you elaborate on the two versions, which versions specifically?

**Comment by m50S79sM6SRNp8Jn** [comment]
How you tried reflashing the SD card?

**Comment by m50S79sM6SRNp8Jn** [comment]
Can you try with SD card, use the latest image.

**Comment by ThomasVon2021** [comment]
> I am using a USB key instead of SD card (not sure if this could be the issue). I got this RPi4 and HAT working a few months ago but decided to do a clean install to document better the steps for my lab. I am fairly certain I used a USB device since that how I boot all my RPi4.
> 
> I use both version : blikvm-v1-v2-v3-20230924 and blikvm-v1-v2-v3-20231203

The SD card startup is not related to the hat itself, but only depends on the pi4b and SD card

**Comment by ThomasVon2021** [comment]
If it has not been resolved yet, please open this issue again. And provide more information.
