### ISSUE TITLE
[Bug] [BliKVM v4 v2.2] WebUI keep resizing the video stream

### ISSUE THREAD

**Issue by ds2812** [ThomasVon2021/blikvm#155]
The WebUI keep resizing the video stream from the client according to the browser size.
Could you make an option to keep the video stream fixed at ustream output resolution (1080p by default)?

**Comment by m50S79sM6SRNp8Jn** [comment]
Which software version you are using?
Which video type, h264 or mjpeg?
Which BliKVM device did are buy?

**Comment by ds2812** [comment]
Which software version you are using? - 2.2 (I've switched to piKVM now, cannot verify)
Which video type, h264 or mjpeg? - MJPEG
Which BliKVM device did you buy? - BLIKVM V4

**Comment by ThomasVon2021** [comment]
You can try to update 1.4.3 alpha to test.

**Comment by ThomasVon2021** [comment]
You can update to version v1.4.7 alpha for testing now. If there are still issues, you can reopen this problem
