### ISSUE TITLE
[Feature] [BliKVM v4] Enhanced Display Management and Automation Features

### ISSUE THREAD

**Issue by jchurchward** [ThomasVon2021/blikvm#158]
Could a screensaver feature be implemented on the Allwinner V4's display, allowing it to be deactivated by pressing a button on the front panel if someone needs to view the content?

Additionally, it would be advantageous to have the ability to dim the display and even schedule when the display is active. The possibility of controlling these features through an API, enabling their management via NodeRed automations, would be incredibly useful as well.

**Comment by ThomasVon2021** [comment]
https://wiki.blicube.com/blikvm/en/OLED-display/
