### ISSUE TITLE
[Feature Request] Real Full Screen without resizing video

### ISSUE THREAD

**Issue by Er-i-c** [ThomasVon2021/blikvm#159]
I use an extra Full HD monitor for blikvm. The problem is that the image is blurred because of the left panel even though I use full screen.
Would be nice to have video without resizing.

As a workaround I use the Developer Tools to delete the leftmenu div and the div styles in the videocontainer and webrtc-output. I also remove the padding on videocontainer. These changes are not persistent, so I need to redo this every time.

Maybe the left menu can appear floating over the video when the mouse hits the border (without resizing)?

Thanks

**Comment by ThomasVon2021** [comment]
https://wiki.blicube.com/blikvm/en/flashing_os/
You can flash the lasted image to test.

**Comment by ThomasVon2021** [comment]
Upgrade to the latest version, and if there are any issues, you can reopen it.
