### ISSUE TITLE
[Question][KVM switch] Using multiple devices without adding a KVM switch

### ISSUE THREAD

**Issue by marino-mrc** [ThomasVon2021/blikvm#162]
Hello,
I have a question about multiple clients and Blikvm.

Can I use multiple RP2040 devices and a shared SPI bus with GPIOs used as a "chip select" and switch from one keyboard to another? Also, can I use multiple HDMI to USB devices and switch from one monitor to another?

I know this feature is missing at the moment, but can this be considered as something to be investigated? I'm also available to help if a driver is needed for the SPI communication.

Thanks,
Marco

**Comment by ThomasVon2021** [comment]
We may not consider doing this for the time being, as we are preparing to release a switch containing ATX
