### ISSUE TITLE
[Feature Request] [BliKVM v4] Add mouse jiggler

### ISSUE THREAD

**Issue by mareksagan** [ThomasVon2021/blikvm#173]
Please add a mouse jiggler to BliKVM v4 so the computer doesn't go to sleep

**Comment by ThomasVon2021** [comment]
This can be added in the new version.

**Comment by ThomasVon2021** [comment]
https://wiki.blicube.com/blikvm/en/flashing_os/
You can flash the lasted image to test.

**Comment by ThomasVon2021** [comment]
The latest v1.4.4 version has been tested and is now supported. If there are any issues, you can reopen it
