### ISSUE TITLE
[Bug] [BliKVM v4] Image/Stream is draggable

### ISSUE THREAD

**Issue by rwardlow01** [ThomasVon2021/blikvm#175]
Please add: draggable="false"
to the img tag like this:
`<img id="webrtc-output" draggable="false" src="http://192.168.1.244:8008/stream?advance_headers=1" style="width: 1162px; height: 653.625px;">`
this will prevent dragging the image element when trying to do a left click drag on the remote computer

**Comment by ThomasVon2021** [comment]
I wiil try this

**Comment by ThomasVon2021** [comment]
![image](https://github.com/user-attachments/assets/0b9902a1-ac6a-4be3-a2e1-fe15da96e482)
The new version has not yet been released and the software has added this parameter. Thank you for your suggestion.

**Comment by ThomasVon2021** [comment]
https://wiki.blicube.com/blikvm/en/flashing_os/
You can flash to the lasted image to test.

**Comment by ThomasVon2021** [comment]
Upgrade to the latest version, and if there are any issues, you can reopen it.
