### ISSUE TITLE
[Feature Request] Record screen

### ISSUE THREAD

**Issue by xinchaohe** [ThomasVon2021/blikvm#183]
When I remote my PC with blikvm, I would like to caputer the screen to make a video.  I can't find screen recorder function. Could you please add this function in Blikvm system next version?

**Comment by m50S79sM6SRNp8Jn** [comment]
/api/video/record

**Comment by m50S79sM6SRNp8Jn** [comment]
Duplicate https://github.com/ThomasVon2021/blikvm/issues/222
