### ISSUE TITLE
Issue running BliKVM v4 update script

### ISSUE THREAD

**Issue by pjnaughter** [ThomasVon2021/blikvm#186]
I'm trying to update my BliKVM v4 using the "Manually run the script to update" at [https://wiki.blicube.com/blikvm/en/update/#manually-run-the-script-to-update](https://wiki.blicube.com/blikvm/en/update/#manually-run-the-script-to-update). When I run the line of the script "python3 /opt/bin/blikvm/script/update.py" I get the following:

Board type: BoardType.V4_H616
The latest release tag for blikvm is  v1.4.4
The local version is  Develop-1.3.8
Upgrading  Develop-1.3.8  ==>  v1.4.4
Download package:  release-h616-v4.tar.gz  please wait...
**_Could not find asset with name release-h616-v4.tar.gz_**
Download release package success, start to install, please wait 60s...
root@mangopimcore:/opt/bin/blikvm#

Can someone tell me why the script is reporting the "Could not find asset with name ..." error or is there a issue with the update scripts?

Thanks in advance

**Comment by ThomasVon2021** [comment]
![image](https://github.com/user-attachments/assets/d7ad19d9-a515-4470-91ba-12eef51d89e2)
https://wiki.blicube.com/blikvm/en/update/#introduction
Need add alpha.

**Comment by pjnaughter** [comment]
Thanks very much for that. I was not aware that I needed to use the alpha command line parameter. Just updated now and the UI now looks much improved. Thanks for a great project.
