### ISSUE TITLE
[Enhancement] [1.4.4-alpha] send alt+ctl+del missing

### ISSUE THREAD

**Issue by mrulke** [ThomasVon2021/blikvm#187]
im unable to send combination keys to the session.
could do this on the old version via the configured macros but they are missing now.

**Comment by ThomasVon2021** [comment]
Yes, I will add it to 1.4.5 this week.

**Comment by mrulke** [comment]
wow so quick

**Comment by ThomasVon2021** [comment]
This time, it supports custom shortcut keys. Later, I will write an explanation on how to customize the configuration.
