### ISSUE TITLE
Updated to [1.4.5-alpha] - cannot log in to web interface anymore

### ISSUE THREAD

**Issue by swingstate** [ThomasVon2021/blikvm#190]
I upgraded through the ssh script from any earlier 1.4.x build. 
Update went fine, rebooted. 
Now, I cannot login with the account defined in the admin.ini anymore. 

Any advice?

**Comment by mircea-pavel-anton** [comment]
Is the web UI not showing up or are the credentials just not working? I also ran into this and I just rebooted once more and it came back up

**Comment by ThomasVon2021** [comment]
> I upgraded through the ssh script from any earlier 1.4.x build. Update went fine, rebooted. Now, I cannot login with the account defined in the admin.ini anymore.
> 
> Any advice?

Default is reset to admin/admin

**Comment by swingstate** [comment]
That was too easy. Thanks Thomas. Is that reset documented somewhere and will that happen with every reset in the new version?

Do we still need the admin.ini?

**Comment by ThomasVon2021** [comment]
In version 1.4.6, there will be no reset, you can try it out.
Don't need admin.ini anymore.
