### ISSUE TITLE
[Enhancement] [BliKVM v4] Turn off background light on LCD

### ISSUE THREAD

**Issue by jhaveDK** [ThomasVon2021/blikvm#204]
**Problem Description**
The LCD background light is not turn off when the LCD is turn off. Please see images 

**Proposed Solution**
Turn the background light off when its turn off. 

**Alternatives Considered**
N/A

**Additional context**
Please see images. 
![LCD2](https://github.com/user-attachments/assets/60eb3418-159f-4f4c-b9d0-155ab67cad2f)
![LCD1](https://github.com/user-attachments/assets/158276e9-9fd9-422c-955b-aa52bea52836)

**Comment by ThomasVon2021** [comment]
We will fix this in later version.

**Comment by m50S79sM6SRNp8Jn** [comment]
Hi @jhaveDK,

When you have a moment, how is this issue different from https://github.com/ThomasVon2021/blikvm/issues/194 ?
