### ISSUE TITLE
WebUI for uploading and mounting images

### ISSUE THREAD

**Issue by SchoolGuy** [ThomasVon2021/blikvm#21]
As stated by [the docs](https://wiki.blicube.com/blikvm/en/msd/#upload-images-through-web-ui) the feature is under development. Is there anything one can do to speed up this process? At the moment this is a major disadvantage compared to  pikvm imho.

**Comment by ThomasVon2021** [comment]
I am striving to release this UI feature in the next month. Thank you for your attention

**Comment by SchoolGuy** [comment]
@ThomasVon2021 Thank you for this quick answer. Looking forward to it!

**Comment by ThomasVon2021** [comment]
You can update to lasted version to test
