### ISSUE TITLE
[Feature Request] Add 2FA support

### ISSUE THREAD

**Issue by m50S79sM6SRNp8Jn** [ThomasVon2021/blikvm#214]

**Comment by adriano-g** [comment]
That would be a great security feature and make it more acceptable for corporations to use it

**Comment by ThomasVon2021** [comment]
First, submit a universal API for v1-v4 that only supports recording mjpeg. We need to design it separately here. v1-v3 can record sound, but v4 cannot

**Comment by m50S79sM6SRNp8Jn** [comment]
Available in v1.5.3-alpha release

**Comment by MillionMilerClub** [comment]
That's great, thank you.
