### ISSUE TITLE
Popup with "Current temp CPU"

### ISSUE THREAD

**Issue by Enzokot** [ThomasVon2021/blikvm#22]
As a suggestion. May be add here popup with "Current temp CPU"?
![2023-05-25_11-14-17](https://github.com/ThomasVon2021/blikvm/assets/43236573/ab7f8ee7-5775-4bc1-a0ae-bc98a33b918c)

**Comment by ThomasVon2021** [comment]
Ok, we will add this function. Thanks.

**Comment by m50S79sM6SRNp8Jn** [comment]
Suggestion, output: 

104F / 40C

**Comment by ThomasVon2021** [comment]
Ok

**Comment by ThomasVon2021** [comment]
Done.
https://github.com/ThomasVon2021/blikvm/releases/tag/Develop-1.1.3

**Comment by Enzokot** [comment]
@ThomasVon2021 
May be popup like this?
![image](https://github.com/ThomasVon2021/blikvm/assets/43236573/8f40726d-8c4b-470b-b6e7-54e76a711cef)

**Comment by ThomasVon2021** [comment]
The plan is to create a graph of how many times the delay graph has been updated in the future.

**Comment by ThomasVon2021** [comment]
Okay, it will be updated in the future.

**Comment by m50S79sM6SRNp8Jn** [comment]
This will be addressed in our new BliKVM Matrix release, tentatively Q1/Q2 2024.

**Comment by m50S79sM6SRNp8Jn** [comment]
This will be addressed in our new BliKVM Matrix release, tentatively Q1/Q2 2024.
