### ISSUE TITLE
[BUG][1.5.1]Double consecutive characters are not pasted using Text/Paste feature

### ISSUE THREAD

**Issue by pdeliot** [ThomasVon2021/blikvm#225]
**Problem Description**
Double characters are not pasted using Text/Paste feature

**Proposed Solution**
do not loose character during paste :-) 

**Additional context**
No character loss if it is not a duplicate:
abcd will put abcd
aabbccdd will put abcd :-(

![image](https://github.com/user-attachments/assets/94620484-9ef3-4669-a9eb-301c3e9d7de9)

**Comment by ThomasVon2021** [comment]
We will fix it in v1.5.2.

**Comment by ThomasVon2021** [comment]
Released v1.5.2-alpha, you can update to test.

**Comment by pdeliot** [comment]
Solved

**Comment by pdeliot** [comment]
Solved
