### ISSUE TITLE
blikvm emmc health

### ISSUE THREAD

**Issue by erlendoyen** [ThomasVon2021/blikvm#233]
Hi

is there a way to check the health of the emmc storage?

it's the BliKVM V4 Allwinner H616

i have tested using mmc, but not able to get any data.

it would be nice to show the health of the storage in the ui.

**Comment by ThomasVon2021** [comment]
H616 core doesn't have emmc; it uses an SD card.

**Comment by erlendoyen** [comment]
ah ok.
