### ISSUE TITLE
[Enhancement] Strings for localization

### ISSUE THREAD

**Issue by Enzokot** [ThomasVon2021/blikvm#24]
Can't find some strings for localization web UI (third_lib/Multi_language/en.js)
1. Text under username and button text
![image](https://github.com/ThomasVon2021/blikvm/assets/43236573/ce1f1324-8efa-4f7b-ac21-b9dc5380d6dd)

2. Text for popup balloon after login
![image](https://github.com/ThomasVon2021/blikvm/assets/43236573/d3cd4ac1-c46c-44b3-a263-3c0a83e77608)

3. Text for popup balloon after no update found
![image](https://github.com/ThomasVon2021/blikvm/assets/43236573/4666c74f-314e-4a1e-baaa-f240822914d5)

4. Button text on warning window for Reset ATX
![image](https://github.com/ThomasVon2021/blikvm/assets/43236573/369bf8b1-5aff-40c5-b6c2-95cd7cdb146a)

5. Text for titles "Version" and "Build", button text for current version Bli KVM
![image](https://github.com/ThomasVon2021/blikvm/assets/43236573/0c7a89cb-6b12-417e-bc53-7340d1c1e564)

6. Text for new popup with current temp and button text
![image](https://github.com/ThomasVon2021/blikvm/assets/43236573/ccd724be-4cb6-4a9b-bc46-0e508c3c280d)

**Comment by ThomasVon2021** [comment]
Received, we will notify you after the repair.

**Comment by ThomasVon2021** [comment]
3. Text for popup balloon after no update found
Is there any problem with this sentence? I am currently fixing it.

**Comment by Enzokot** [comment]
>    Is there any problem with this sentence? I am currently fixing it.
Can't find in the file "third_lib/Multi_language/en.js" only

**Comment by Enzokot** [comment]
Additionally can't find sting for empty password

![image](https://github.com/ThomasVon2021/blikvm/assets/43236573/074077b2-0ae8-420c-a638-4772235587c6)

**Comment by ThomasVon2021** [comment]
Can you update to 1.3.9 to test. I update ui lib to solve this problem.

**Comment by m50S79sM6SRNp8Jn** [comment]
1.3.9 resolved the issue

**Comment by ThomasVon2021** [comment]
These issues have been resolved in the latest version. If you still find them, please resubmit the issue.
