### ISSUE TITLE
Include copyright notice for third-party code

### ISSUE THREAD

**Issue by mtlynch** [ThomasVon2021/blikvm#3]
[`./package/kvmd-hid/enable-gadget.sh`](https://github.com/ThomasVon2021/blikvm/blob/6416500adf4436f3bf009d421dd93baad88a30eb/package/kvmd-hid/enable-gadget.sh) seems to be derived from TinyPilot's copyrighted code here:

https://github.com/tiny-pilot/ansible-role-tinypilot/blob/master/files/init-usb-gadget

[`./package/kvmd-hid/disable_gadget.sh`](https://github.com/ThomasVon2021/blikvm/blob/6416500adf4436f3bf009d421dd93baad88a30eb/package/kvmd-hid/disable_gadget.sh) seems to be derived from TinyPilot's copyrighted code here:

https://github.com/tiny-pilot/ansible-role-tinypilot/blob/master/files/remove-usb-gadget

TinyPilot's code is released [under the MIT license](https://github.com/tiny-pilot/tinypilot/blob/master/LICENSE), so you're welcome to include it, but the license requires preserving the copyright notice and license.

You can get back into compliance with the license this by copying the text from [TinyPilot's license](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/master/LICENSE) as a header at the top of each derived file or by including TinyPilot's license in a file called `NOTICE` at the root of the repo.

**Comment by mtlynch** [comment]
Moved to the correct repo

**Comment by ThomasVon2021** [comment]
https://github.com/ThomasVon2021/blikvm/blob/master/package/kvmd-hid/disable_gadget.sh
https://github.com/ThomasVon2021/blikvm/blob/master/package/kvmd-hid/enable-gadget.sh
Thank you for reminding me. It's correct.

**Comment by mtlynch** [comment]
Thanks!

**Comment by mtlynch** [comment]
@ThomasVon2021 - The license notice was removed in https://github.com/ThomasVon2021/blikvm/commit/74b7bd0d8df57922b05f207716411421b16dcc67#diff-13cf57767c8d201ac67a5de3c2f07904a3b64bb3e48075446c10c31f14f68c77

You're required to either remove the file or preserve the license.

**Comment by ThomasVon2021** [comment]
https://github.com/ThomasVon2021/blikvm/commit/0deef067b4d728074f35037841a0f2b41acabb66
Thank you for your remind.

**Comment by ThomasVon2021** [comment]
I have a question to ask you. I use GPL-3.0 license for other code, should I also add this description to all my original code?

**Comment by mtlynch** [comment]
@ThomasVon2021 - I see you've again marked this as completed without actually complying with the license. Please link to where the license has been honored. Otherwise, you are still in violation of TinyPilot's MIT License.

**Comment by ThomasVon2021** [comment]
<img width="809" alt="截屏2024-08-29 00 08 34" src="https://github.com/user-attachments/assets/cf96b64b-02b6-497d-9920-971d04f506b2">
![Uploading 截屏2024-08-29 00.08.43.png…]()

**Comment by ThomasVon2021** [comment]
> <img alt="截屏2024-08-29 00 08 34" width="809" src="https://private-user-images.githubusercontent.com/45224459/362367584-cf96b64b-02b6-497d-9920-971d04f506b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NjE3MzYsIm5iZiI6MTcyNDg2MTQzNiwicGF0aCI6Ii80NTIyNDQ1OS8zNjIzNjc1ODQtY2Y5NmI2NGItMDJiNi00OTdkLTk5MjAtOTcxZDA0ZjUwNmIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDE2MTAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0ODNjYzA1MTkxZDBmZGNhZDdjYzg0M2QwMjhmYmIyYzdiZTNmYjczOWIzZTBmMjc5MDViZjExOTJjYjk4MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ssVzYNmAm9yU71DHRNogyIogG45IyIotY56rYnbGI5w"> ![Uploading 截屏2024-08-29 00.08.43.png…]()

It hasn't been modified, it's kept, right?

**Comment by ThomasVon2021** [comment]
https://github.com/ThomasVon2021/blikvm/blob/master/package/kvmd-hid/enable-gadget.sh
https://github.com/ThomasVon2021/blikvm/blob/master/package/kvmd-hid/disable-gadget.sh

Still retained and not removed, please help point out the specific issues.

**Comment by mtlynch** [comment]
Sorry, you're correct. I didn't realize that the link in the original comment was to an old commit rather than the latest in master.
