### ISSUE TITLE
[Feature Request] Settings new features

### ISSUE THREAD

**Issue by NeVa0Theresia** [ThomasVon2021/blikvm#34]
+Reboot option for BliKVM itself
+SSH shell support

**Comment by ThomasVon2021** [comment]
add Reboot option;

**Comment by ThomasVon2021** [comment]
We will start considering adding SSH shell this year

**Comment by NeVa0Theresia** [comment]
> We will start considering adding SSH shell this year

Really appreciate it. Thanks

**Comment by m50S79sM6SRNp8Jn** [comment]
Good news, these two features will be made available fairly soon.

**Comment by m50S79sM6SRNp8Jn** [comment]
Recommend you upgrade to latest version v.1.4.6-alpha (or higher). The features are available there.

**Comment by NeVa0Theresia** [comment]
Thanks to the dev team! Featrures have been added to the new ui. I updated v4 from 1.4.0 to 1.4.x, the redesigned web ui would clear the previous web ui config, especially web login credentials; therefore i recommand displaying a warning or notification during the update on the terminal.

**Comment by ThomasVon2021** [comment]
> 感谢开发团队！新 UI 中添加了功能。我将 v4 从 1.4.0 更新到 1.4.x，重新设计的 Web UI 将清除以前的 Web UI 配置，尤其是 Web 登录凭据；因此我建议在终端上更新期间显示警告或通知。

Will add warn, thank you.
