### ISSUE TITLE
[Feature Request] Hide the control panel on webGUI to maximize the operate area

### ISSUE THREAD

**Issue by amplatzer** [ThomasVon2021/blikvm#35]
<img width="762" alt="image" src="https://github.com/ThomasVon2021/blikvm/assets/3972924/4a86ba3a-ad61-46b8-9910-efb75b0bc448">

Hide the panel so we can get almost 1980x1080 on full-screen mode.

**Comment by ThomasVon2021** [comment]
update to 1.4.3 alpha version
https://wiki.blicube.com/blikvm/en/update/
