### ISSUE TITLE
[Bug] Password change should take effect immediately 

### ISSUE THREAD

**Issue by amplatzer** [ThomasVon2021/blikvm#36]
make no sense to restart the GUI to take effect.

**Comment by ThomasVon2021** [comment]
Do you mean when change password, the web should exit immediately?

**Comment by amplatzer** [comment]
> Do you mean when change password, the web should exit immediately?

不， 现在修改完密码，好像需要重启 kvm-link 才会生效， 我希望马上生效，至少当前会话需不需要强制退出， 这个倒是无所谓，最好是强制退出吧。

**Comment by ThomasVon2021** [comment]
好的，已加入开发计划，更新后告诉你

**Comment by m50S79sM6SRNp8Jn** [comment]
resolved in 1.3.9
