### ISSUE TITLE
blikvm crash with intel nuc 12 pro

### ISSUE THREAD

**Issue by to4ko** [ThomasVon2021/blikvm#43]
Trying to run blikvm (edid for 1080p50hz) with my nuc 12 pro  leads to blikvm restart while nuc shutsdown. More over, nuc cannot be started after that with power button. Only psu disconnection helps. Nothing in logs. Sametime blikvm works perfectly fine with other my pc.

**Comment by ThomasVon2021** [comment]
BlikVM software have some progress, like kvmd-main and kvm-link, can you tell which program has a problem when you manually execute it?

**Comment by to4ko** [comment]
> BlikVM software have some progress, like kvmd-main and kvm-link, can you tell which program has a problem when you manually execute it?

Will do ASAP - right now this NUC in production and there is no options to "test". Soon new NUC will arrive and i will do tests.

**Comment by ThomasVon2021** [comment]
Okay, waiting for your results.

**Comment by to4ko** [comment]
so. if USB is not connected - no problem at all. once USB connected to NUC (USB 2.0 port) - everything shuts down

if i run kvmd-main

![image](https://github.com/ThomasVon2021/blikvm/assets/45161980/177c87c8-49eb-4157-87f1-40ab7650e7cd)


and everything shuts down

**Comment by to4ko** [comment]
same behaviour with USB2.0 port and USB3.0 port.

any specific settings might be applied in NUC BIOS?

**Comment by ThomasVon2021** [comment]
Can you use gdb run, to get the bt?

**Comment by to4ko** [comment]
> Can you use gdb run, to get the bt?

could you please elaborate a little bit - i don't get what i need to do

**Comment by to4ko** [comment]
as i proposed - it's all about usb settings in nuc. all kind of charging supposed to be turned off for port used to connect with blikvm
