### ISSUE TITLE
UX Improvement: Keyboard Macros

### ISSUE THREAD

**Issue by bartlanz** [ThomasVon2021/blikvm#45]
Have a way on the onscreen keyboard and/or on the left side menu to do pre-defined macros, ideally customizable by the end user. Things like pressing Control + Alt + Delete or FN+ F5 for swapping screen outputs.

**Comment by ThomasVon2021** [comment]
Okay, this requirement is under development.

**Comment by ThomasVon2021** [comment]
Upgraded to the current version 1.3.9 and beyond, the virtual keyboard has added the function of fixed combination keys, which is not currently supported for complete customization. It is expected to be considered to be added in future versions.
