### ISSUE TITLE
Keyboard Setting: CMD Vs Win

### ISSUE THREAD

**Issue by bartlanz** [ThomasVon2021/blikvm#46]
Add a setting to change the CMD button to say WIN or show the windows logo

**Comment by ThomasVon2021** [comment]
Your requirements have been noted and will be developed

**Comment by ThomasVon2021** [comment]
I think the CMD button needs to be adapter to the target system. But use HDMI or USB, kvm doesn't know the target system. So maybe I think if it can't auto. That doesn't make much sense.

**Comment by m50S79sM6SRNp8Jn** [comment]
Not planned
