### ISSUE TITLE
HDMI switch issue

### ISSUE THREAD

**Issue by to4ko** [ThomasVon2021/blikvm#54]
i'm running blikvm hat with hdmi kvm switch. but no control from blikvm gui available. also there is no ttyUSB0 device appearing once control usb cable connected. is there any tricks like special usb cable or smthg else?

switch working well with remote device and using hardware buttons on it. "link" and "power" led's is on once cables connected.

![image](https://github.com/ThomasVon2021/blikvm/assets/45161980/5b26af2b-752f-49d2-a278-8dca4f4c016d)

**Comment by ThomasVon2021** [comment]
https://wiki.blicube.com/blikvm/en/switch-guide/#introduction
Yes, there are special wires, and there is a wire labeled kvm for this purpose. Please check the specific wiring on the wiki, and if convenient, you can take photos.

**Comment by to4ko** [comment]
Ah. I see. Most probably it's all about the "special" canle. Any chance to buy it or get pinouts/schemes to make my own?

**Comment by ThomasVon2021** [comment]
Our packaging is already equipped with this kvm control line and labeled, isn't it in your package?

**Comment by to4ko** [comment]
unfortunately i don't have it as i used switch from another project. it was already on hand and there was no reason to buy new one.

**Comment by ThomasVon2021** [comment]
Does your switch support remote switching? If the switch you are using does not support control itself, then there is no way.
If it is supported by itself, but the protocol is different, it can be supported through software development.

**Comment by to4ko** [comment]
i't same XH-HK4401 as one you selling. only thing i'm missing is "USB remote cable"

![image](https://github.com/ThomasVon2021/blikvm/assets/45161980/e8ae76a3-8756-4d7e-824b-c7a389f2118f)

**Comment by ThomasVon2021** [comment]
Currently, there are no products purchased separately from this line, as cross-border express delivery is expensive and it is difficult to sell on a separate line.

**Comment by to4ko** [comment]
ok. i et you point. will make my own cable.

**Comment by to4ko** [comment]
solved with locally purchased ftdi module
