### ISSUE TITLE
Save Video settings when refreshing UI.

### ISSUE THREAD

**Issue by DrDrache** [ThomasVon2021/blikvm#59]
in the settings when I choose 16:9 (or another ratio) to match my screen - this setting is reset if there is a timeout (sleeping tab) or you refresh the UI for any reason. 
As you are not switching Hosts, we should be able to save these settings so that they stay on refreshes/reboots.

save settings for all settings, or persist the video settings would be nice!

**Comment by ThomasVon2021** [comment]
Okay, great suggestion, I will let you know after the update. The expected strategy is to save during the current session cycle of the browser.

**Comment by ThomasVon2021** [comment]
You can update to Develop-1.2.3 to test, if you find any problem, please tell us.
