### ISSUE TITLE
[Feature Request] Add 'Mouse polling rate' option

### ISSUE THREAD

**Issue by kywarai** [ThomasVon2021/blikvm#61]
Feature Request: Add a Mouse Polling Rate option, similar to that in PiKVM, for adjusting the polling rate of mouse actions. 
Shortening the polling interval can make mouse movement smoother.

Here's the option in the PiKVM, the option in PiKVM is actually an interval time, the smaller the value, the higher the polling rate.
![image](https://github.com/ThomasVon2021/blikvm/assets/62436209/9f560b3b-0200-49f0-91cb-f06673b3fae1)

ref: https://github.com/pikvm/kvmd/blob/988a190957a367ed7a4b177b428507135d37709c/web/share/js/kvm/mouse.js#L115

**Comment by m50S79sM6SRNp8Jn** [comment]
We plan to deliver this feature as part of our new BliKVM Matrix release, tentatively Q1/Q2 2024.

**Comment by ThomasVon2021** [comment]
Considering network transmission, the mouse speed is currently adaptive, so this feature will not be added temporarily.
