### ISSUE TITLE
Feature request: add Ctrl+Alt+Del button to the toolbar

### ISSUE THREAD

**Issue by harlong** [ThomasVon2021/blikvm#62]
![image](https://github.com/ThomasVon2021/blikvm/assets/116577111/d5769258-9e47-4e5d-94e7-0afa590c4558)
Can you add a button "Ctrl+Alt+Del" to this toolbar? Now for this combination i have to open on-screen keyboard, press Ctrl+Alt on my keyboard and click "Del" with the mouse

**Comment by ThomasVon2021** [comment]
Yes, we will develop it.

**Comment by ThomasVon2021** [comment]
You can update to 1.2.4 version to use this function. you can open the virtual keyboard to use it.
