### ISSUE TITLE
Feature request: add a "hard power off" or "press and hold power" option

### ISSUE THREAD

**Issue by harlong** [ThomasVon2021/blikvm#63]
![image](https://github.com/ThomasVon2021/blikvm/assets/116577111/c5ef6b34-c582-4255-b983-e08c0a38f4bb)
Can you add an option to "Press and hold power switch" or "hard power off"? In most ATX systems to turn off the stalled PC i must hold "Power" for at least 3-5 seconds

**Comment by ThomasVon2021** [comment]
Doe now can't power off? The latest version atx poweroff default time is 5 seconds.

**Comment by ThomasVon2021** [comment]
Ok, If you update to the latest version, still work, I think maybe I put the time config will be also ok?

**Comment by harlong** [comment]
Yes, it may be a good idea

**Comment by harlong** [comment]
Yes, i tested on dev-1.1.8, then it was 2 seconds

**Comment by ThomasVon2021** [comment]
when you update to 1.2.0，is it ok？

**Comment by harlong** [comment]
I think it is ok, but i can not check, because my server is not freezing anymore

**Comment by ThomasVon2021** [comment]
You can change the power on or off delay time in the 1.2.7 version. The config file is in /usr/bin/blikvm/package.json
