### ISSUE TITLE
[Enhancement][1.2.8] Web UI translation issues

### ISSUE THREAD

**Issue by harlong** [ThomasVon2021/blikvm#64]
![image](https://github.com/ThomasVon2021/blikvm/assets/116577111/99aaff99-f0cc-4d5a-b182-73f15fce67f8)
1. Button and warning messages on login form are not translated

![image](https://github.com/ThomasVon2021/blikvm/assets/116577111/e6f43f6c-39a8-4924-a0ef-40e3d6085167)
2. Buttons on reset confirmation form are not translated

![image](https://github.com/ThomasVon2021/blikvm/assets/116577111/cfe664bf-4a72-4636-a90b-7108fc2a691e)
3. Button on version information form is not translated

4. In the /opt/bin/blikvm/third_lib/Multi_language there is a French translation, but it's unavailable in language settings.
5. I have sent you a russian translation, but it's too yet not included

**Comment by harlong** [comment]
[ru.js.zip](https://github.com/ThomasVon2021/blikvm/files/12833413/ru.js.zip)

**Comment by ThomasVon2021** [comment]
I will check it, thank you.

**Comment by melroy89** [comment]
I have the same issue. Also those labels as still Chinese. Even the notifications I get are still in Chinese:

![image](https://github.com/ThomasVon2021/blikvm/assets/628926/aac94b5e-b977-484f-ad65-94476a1d4352)

**Comment by melroy89** [comment]
https://github.com/ThomasVon2021/blikvm/issues/24 is related.

Do you know the root-cause already?

**Comment by devzwf** [comment]
same in French
would be interesting to update those

**Comment by harlong** [comment]
Upgraded to dev-1.2.8:
- When checking for updates, popup "No higher version fetched" is not translated
- "Power ON" label in web GUI should be changed to "On/Off" (see discord "dev" chat)
- "Power OFF" label should be changed to "Force off" (see discord "dev" chat)
- After "Version information:" in "More" screen space is missing
- In "Send text" menu, caption is not translated (see pic belos)
- "In development" in MSD is not translated
- In change password form after "strength:' space is missing
- On login form two warning messages and confirmation button are not translated (see pic below)
- "Successful login" notice is not translated (see pic below)
- Text in "Device is offline" warning is not wrapped to the next line, and is just cut off (see pic below)
- "Language" in additional menu is not translated
- Russian text width is still somehow weird, i don't know, how to shorten it (see pic below)
- Anyhow, i've committed an updated ru.js

![image](https://github.com/ThomasVon2021/blikvm/assets/116577111/e73f15db-3a1d-4af4-adc6-f96d5bd2faa4)
![image](https://github.com/ThomasVon2021/blikvm/assets/116577111/7a937e78-0bf6-4b88-9b27-f825aaaa69ab)
![image](https://github.com/ThomasVon2021/blikvm/assets/116577111/0b70cc7a-4f08-4691-bdb5-7c7c7bad8289)
![image](https://github.com/ThomasVon2021/blikvm/assets/116577111/554736a9-5ef6-4c00-b52d-2769f74a2cf0)
![image](https://github.com/ThomasVon2021/blikvm/assets/116577111/d0ba6bac-6e6a-4f08-8eb1-6669a43befc5)
![image](https://github.com/ThomasVon2021/blikvm/assets/116577111/2cdfbdc6-19f2-4adb-9d93-65061b9b343b)

**Comment by harlong** [comment]
One more Chinese text that is not translated

![image](https://github.com/ThomasVon2021/blikvm/assets/116577111/3e52ae7c-6986-4fe8-a005-98fd104170d4)

**Comment by ThomasVon2021** [comment]
https://wiki.blicube.com/blikvm/en/flashing_os/
You can flash the lasted image to test.

**Comment by melroy89** [comment]
Or by upgrading, right? https://wiki.blicube.com/blikvm/en/update/

**Comment by ThomasVon2021** [comment]
yes, use alpha
