### ISSUE TITLE
[Feature request] ATX module/library/script

### ISSUE THREAD

**Issue by srepac** [ThomasVon2021/blikvm#77]
Per our conversation, in order to support ATX with pikvm software on blikvm v4 hardware, we need something similar to kvmd-msd.sh to support ATX controls.

I have been able to run pikvm software on the blikvm v4 hardware and in order to have MSD support, I'm using the built-in kvmd-msd.sh script from blikvm to make/connect/disconnect the ventoy image to the target system by running the kvmd-msd.sh script in ssh/web terminal.

I am requesting something similar to support ATX as the v4 hardware does not use the same GPIO pins for ATX support in pikvm.

**Comment by ThomasVon2021** [comment]
Can you test it? 
https://github.com/ThomasVon2021/blikvm/tree/master/package/kvmd-atx
