### ISSUE TITLE
Missing OLED python dependency

### ISSUE THREAD

**Issue by jhg03a** [ThomasVon2021/blikvm#9]
For the python oled script to start you have to install pip and `pip3 install adafruit-circuitpython-ssd1306`

**Comment by ThomasVon2021** [comment]
Do you mean 'pip install adafruit-circuitpython-ssd1306" can't install?

**Comment by ThomasVon2021** [comment]
https://github.com/ThomasVon2021/blikvm/blob/master/dev-readme.md

**Comment by jhg03a** [comment]
This was a brand new stock image of a PCIe model blikvm
